# -*- coding: utf-8 -*-
"""Connection To DB_Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iGO5lCPWWoA1yixiYI94ZMpfvP4C71YL

# Connection to Database using Python

##### Required installations
"""

!pip install db-sqlite3

"""##### Imports"""

import pandas as pd
import sqlite3
from datetime import date

"""##### Connecting to database"""

db = sqlite3.connect("ProjectDatabase.db")

"""##### Check if a table already exists before creation and if so delete it and create new table"""

db.execute("drop table if exists projectData")
try:
  db.execute("create table projectData(Name text, DOB datetime, Email_ID text)")
except:
  print("Table already exists!!")

"""##### Take some dummy data to insert in table"""

Names = ['Mike', 'John', 'Karine'] 
DOBs = [date.today().strftime("%m-%d-%Y"), "04-20-1997", "09-18-1993"]
Email_IDS = ['mike@gmail.com', 'john97@yahoo.com', 'kar93ine@abc.edu']

"""##### Put above data in table"""

for i in range(len(Names)):
  insertCmd = "insert into projectData(Name, DOB, Email_ID) values ('{}', '{}', '{}')".format(Names[i], DOBs[i], Email_IDS[i])
  db.execute(insertCmd)
  db.commit()

"""##### Method1: Get data"""

data = db.execute("SELECT * FROM projectData")
for row in data:
  print(row)

"""##### Method2: Get data"""

query = """

SELECT * FROM projectData

"""
df = pd.read_sql_query(query, db)
df.head()